language: haskell
ghc:
  - 8.0
  - 8.6
  - 8.8
  - 8.10
cabal: "2.4"
# script: cabal configure --enable-tests --verbose && cabal build && cabal test	# Exceeds both 10-min/module & 50-min limit for job.
# script: travis_wait 50 cabal configure --enable-tests --ghc-options="-O1" --verbose && cabal build
setup:
  - travis_wait 50 cabal update
